server:
  port: 8888

spring:
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: ${ISSUER_URI:http://localhost:8888/realms/myfit}
cors:
  url: ${CORS_URL:http://localhost:3000}

logging:
  level:
    org:
      springframework:
        security: DEBUG