server:
  port: 8000

api-prefix: /api/back

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: ${api-prefix}/swagger-ui
    enabled: ${SWAGGER_ENABLE:true}
  api-docs:
    enabled: ${SWAGGER_ENABLE:true}

spring:
  liquibase: enable

  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/myfit}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:fit}
    password: ${RABBITMQ_DEFAULT_PASS:pw}


cors:
  url: ${CORS_URL:http://localhost:3000}

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:master}
  username: ${KEYCLOAK_USERNAME:admin}
  password: ${KEYCLOAK_PASSWORD:pw}
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
  queue: ${KEYCLOAK_EVENT_QUEUE:keycloak_back_q}

tuz:
  username: ${TUZ_USER:tuz}
  password: ${TUZ_PASSWORD:password}
