name: maven-test
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: github
          server-username: PACKAGE_USERNAME
          server-password: PACKAGE_PASSWORD
      - name: cache-maven-repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: test
        run: mvn test
        env:
          PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
          PACKAGE_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
      - name: build image
        run: mvn spring-boot:build-image -DskipTests
        env:
          PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
          PACKAGE_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: nexus.fitcycle.online
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}